baseURL = 'https://azoazo.com/'
languageCode = 'zh-tw'
title = 'azo::inheritance'
theme = 'PaperMod'

# 以下內容請貼到你的 config.toml 檔案底部
[params]
    env = "production" # 建議設定為 "production"
    defaultTheme = "light" # 預設主題 ("auto" 根據系統設定，"light", "dark")
    disableThemeToggle = true # 允許使用者切換深色/淺色模式

    [params.label]
        text = "azo::inheritance"
        icon = "/favicon.png" # 網站圖標路徑
        iconHeight = 35

    # 社交媒體圖標 (Social Icons)
    #[[params.socialIcons]]
    #    name = "github"
    #    url = "https://github.com/your_username"

    #[[params.socialIcons]]
    #    name = "twitter"
    #    url = "https://twitter.com/your_username"

    # ... 其他更多 PaperMod 設定 ...
[services]
  [services.googleAnalytics]
    id = 'G-4M0MLQ1EGY'
[taxonomies]
  category = "categories"  # 保留預設
  tag      = "tags"        # 保留預設
[params.author]
  name = "azo"
  # 建議頭像放正方形，路徑放在 static/images/avatar.jpg
  avatar = "favicon.png" 
  bio = "你好，這是我的BLOG，紀錄一些生活想法以及各種創作，歡迎隨時用下面的資訊和我聯絡。"
  
  # 社群連結 (留空則不顯示)
  email = "aazzooccoomm@gmail.com"
  instagram = "https://instagram.com/azo.ccoomm"
  threads = "https://www.threads.net/@azo.ccoomm"
  github = "https://github.com/azoazocom"
  website = "https://azoazo.com"