baseURL = 'https://azoazo.com/'
languageCode = 'zh-tw'
title = 'azo::想告別偏未晚'
theme = 'PaperMod'

# 以下內容請貼到你的 config.toml 檔案底部
[params]
    env = "production" # 建議設定為 "production"
    defaultTheme = "light" # 預設主題 ("auto" 根據系統設定，"light", "dark")
    disableThemeToggle = true # 允許使用者切換深色/淺色模式

    [params.label]
        text = "azo::想告別偏未晚"
        icon = "/favicon.png" # 網站圖標路徑
        iconHeight = 35

    # 社交媒體圖標 (Social Icons)
    #[[params.socialIcons]]
    #    name = "github"
    #    url = "https://github.com/your_username"

    #[[params.socialIcons]]
    #    name = "twitter"
    #    url = "https://twitter.com/your_username"

    # ... 其他更多 PaperMod 設定 ...